const cfGraphql = require('cf-graphql')
const fs = require('fs')
const blueBird = require('bluebird')
const readFile = blueBird.promisify(fs.readFile)
const readdir = blueBird.promisify(fs.readdir)
const {parse} = require('graphql/language')
const {validate} = require('graphql/validation')